In [39]:
import nltk
import pandas as pd
print(nltk.__version__)
%pwd

3.2.5

'/Users/xinyun/Desktop/INST737/Final_Project'

In [40]:
com = pd.read_csv('Comments.csv', encoding="utf-8")
com.head

<bound method NDFrame.head of           Id    PostId  Score  \
0   38814080  24964538      0
1   38814081  24926353      0
2   38814083  24969752      0
3   38814084  24969862      0
4   38814085  24970073      0
5   38814086  24969932      0
6   38814087  24957753      0
7   38814090  24967270      0
8   38814091  24969635      0
9   38814092  24970167      0
10  38814093  24831034      0
11  38814095  24968975      0
12  38814096  24970115      0
13  38814097  24970131      0
14  38814098  24960941      0
15  38814099  24969969      0
16  38814100  24932294      0
17  38814102  24969213      0
18  38814103  24970177      0
19  38814105  24969828      0
20  38814107  24969888      0
21  38814108  24969890      0
22  38814109  24970070      0
23  38814110  24969793      0
24  38814111  24970167      0
25  38814113  24926544      0
26  38814114  24969858      0
27  38814115  24947581      1
28  38814116  10243664      0
29  38814117  14993590      0
..       ...       ...    ...
70  38814171  24969752      0
71  38814172  24969747      0
72  38814173  24969867      0
73  38814174  24962509      0
74  38814176  24970084      0
75  38814177  24970120      0
76  38814178  24970214      2
77  38814179  24938182      0
78  38814181  24969430      0
79  38814183  24970141      1
80  38814184  24970141      0
81  38814185  24970205      0
82  38814186  24935471      0
83  38814187  23124855      0
84  38814188  24969505      2
85  38814190  24892276      0
86  38814192  24953011      0
87  38814193  24970099      0
88  38814194  24969652      0
89  38814195  24966966      0
90  38814196  18383746      0
91  38814197  24911830      0
92  38814200  24968444      0
93  38814202    156868      0
94  38814203  24942333      0
95  38814205  24970199      0
96  38814207  24958789      0
97  38814209  24969134      1
98  38814211  24945944      0
99  38814212  24961092      0

                                                 Text         CreationDate  \
0   In that PHP file, I am getting several databas...  2014-07-26 10:45:07
1   there are always some ways to do things. but i...  2014-07-26 10:45:10
2   @RohitVats ,I use the datagrid for data entry ...  2014-07-26 10:45:17
3   @FrederickCheung: It's just too simple :D Than...  2014-07-26 10:45:18
4   Doh, how did I miss that? Much appreciated, I ...  2014-07-26 10:45:19
5                                I changed I'm trying  2014-07-26 10:45:19
6   @frank Thank you. Well, I put it. (name is SHA...  2014-07-26 10:45:30
7   These are interesting questions. But not reall...  2014-07-26 10:45:52
8                @a_horse_with_no_name next time i'll  2014-07-26 10:46:00
9   The user types numbers and I only want the but...  2014-07-26 10:46:02
10     could you please show code for cropping image?  2014-07-26 10:46:05
11  @laune: Which kinda puts the lie to my *"In fa...  2014-07-26 10:46:29
12  I have used this SlidingMenu library in one of...  2014-07-26 10:46:30
13  I need to get only 16 bytes, and display it as...  2014-07-26 10:46:33
14  Thanks the images seem a little stretched. I f...  2014-07-26 10:46:35
15  you were getting typecast error.. see my edite...  2014-07-26 10:46:38
16  It will be harder than I initially thought, it...  2014-07-26 10:46:52
17  but on the other hand i tried to find wich cod...  2014-07-26 10:46:53
18       Try `split` - I am sure you can look that up  2014-07-26 10:46:58
19  Thanks for the answer, Can you please share a ...  2014-07-26 10:47:03
20  writeFile.createNewFile();  impossible to find...  2014-07-26 10:47:06
21      no..i just want to style name adres and phone  2014-07-26 10:47:08
22       @user3777110 look edited answer in the query  2014-07-26 10:47:12
23  oh..I am doing wrong. I do like this.Then, it ...  2014-07-26 10:47:13
24  You should look at the Validating event of the...  2014-07-26 10:47:15
25  But you can't directly call super because `UIN...  2014-07-26 10:47:25
26    Thank you for your answer.It solved my problem.  2014-07-26 10:47:31
27  First Normal Form is the first in a whole seri...  2014-07-26 10:47:34
28                  thanks, works with 64bit OS too !  2014-07-26 10:47:34
29  The above is exactly I use for my code. If mBl...  2014-07-26 10:47:34
..                                                ...                  ...
70  When you select last row and commit the row (b...  2014-07-26 10:51:15
71  @SimonBlanck - also `init_data` cannot be `und...  2014-07-26 10:51:19
72  can you help me how to use out parameter in fu...  2014-07-26 10:51:27
73  `db_last_insert_id()` was removed in Drupal 7,...  2014-07-26 10:51:29
74  Its perfect fiddler for you: http://jsfiddle.n...  2014-07-26 10:51:38
75            Add the code for loginPanel loginPanelA  2014-07-26 10:51:58
76  `blahzix = tentry.th32OwnerProcessID` doesn't ...  2014-07-26 10:52:05
77  @Sashka, sorry for the excessive comments, I w...  2014-07-26 10:52:08
78  great great great... All goes good.. I removed...  2014-07-26 10:52:13
79                                 No, you shouldn't.  2014-07-26 10:52:17
80     No, you shouldn't use it if you don't need it.  2014-07-26 10:52:24
81  Yeah, as I wrote in the next sentence after th...  2014-07-26 10:52:27
82  @MichaÃ«lAzevedo, you are right about kPFErrorU...  2014-07-26 10:52:28
83  I solved with removing Oracle Java 8 and then:...  2014-07-26 10:52:35
84                              +1 for good update :)  2014-07-26 10:52:40
85  This is just partial solution, it works, but I...  2014-07-26 10:52:55
86  There shouldn't be. Is it always the same type...  2014-07-26 10:52:57
87  Try to follow all the rules as given in link a...  2014-07-26 10:53:01
88  The method xmppRosterDidEndPopulating only wor...  2014-07-26 10:53:06
89  [This example](http://bl.ocks.org/mbostock/388...  2014-07-26 10:53:08
90  @cdhowie, please correct all your claims of <b...  2014-07-26 10:53:18
91  This is great! Thanks. I ended up getting it w...  2014-07-26 10:53:19
92  i fixed that by using ("adminID") yet isnt del...  2014-07-26 10:53:29
93  Your first sentence just isn't true.  When usi...  2014-07-26 10:53:36
94  @ExcelNoobie25. user3879000 makes some excelle...  2014-07-26 10:53:43
95  I have moved the if statement from the button ...  2014-07-26 10:54:01
96  sorry carloseJimenez, yesterday my internet co...  2014-07-26 10:54:02
97  Could this post be of help? http://stackoverfl...  2014-07-26 10:54:22
98  You're welcome. To be honest, I don't think th...  2014-07-26 10:54:24
99    Could you paste `df.head()` into your question?  2014-07-26 10:54:28

   UserDisplayName     UserId
0              NaN  2005071.0
1              NaN  3787750.0
2              NaN  3008788.0
3              NaN  3493998.0
4              NaN  3839120.0
5              NaN  3794651.0
6              NaN  1614697.0
7              NaN   545127.0
8      user3814846        NaN
9              NaN  3872762.0
10             NaN  2122991.0
11             NaN   157247.0
12             NaN  1708743.0
13             NaN  2475484.0
14             NaN   532462.0
15             NaN  3535925.0
16             NaN  2904025.0
17             NaN  3836391.0
18             NaN   892256.0
19             NaN  3741831.0
20             NaN  3832184.0
21             NaN  2119788.0
22             NaN   998158.0
23             NaN  1550974.0
24             NaN  1197518.0
25             NaN   870671.0
26             NaN  3370495.0
27             NaN    19937.0
28             NaN  1084501.0
29             NaN   747873.0
..             ...        ...
70             NaN   632337.0
71             NaN  1558322.0
72             NaN   870561.0
73             NaN   830680.0
74             NaN  2081982.0
75             NaN   449946.0
76             NaN   311966.0
77             NaN  3280533.0
78             NaN  1066828.0
79             NaN   848164.0
80             NaN   663031.0
81             NaN  3212350.0
82             NaN  1523425.0
83             NaN   108742.0
84             NaN   548225.0
85             NaN  3105535.0
86             NaN  1988185.0
87             NaN  1632209.0
88             NaN  3878774.0
89             NaN  1172002.0
90             NaN   352734.0
91             NaN  1874415.0
92             NaN  3879052.0
93             NaN  1081110.0
94             NaN   973283.0
95             NaN  3872762.0
96             NaN  3492813.0
97             NaN  2967091.0
98             NaN  1166087.0
99             NaN  1082349.0

[100 rows x 7 columns]>

In [41]:
com.shape

(100, 7)

In [42]:
positive_terms = []
f = open('positive_terms.txt', "r")
positive_terms = f.read().splitlines()
f.close()

negative_terms = []
f = open('negative_terms.txt', "r")
negative_terms = f.read().splitlines()
f.close()

In [43]:
#remove punctuation
import string

def remove_punctuation(text):
    # Grab the list of standard punctuation symbols that are provided in the string library
    punctuations = string.punctuation # includes following characters: !"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~

    # But don't strip out apostrophes, as we want to preserve possessives and contractions, an alternative would be to expand contractions
    excluded_punctuations = ["'"]
    for p in punctuations:
        if p not in excluded_punctuations:
            # replace each punctuation symbol by a space
            text = text.replace(p, " ") 

    return text

In [44]:
from nltk.tokenize import WhitespaceTokenizer

# Create a tokenizer from NLTK which will create tokens based on the whitespace in between words
tokenizer = WhitespaceTokenizer()

In [45]:
from nltk.corpus import stopwords
stopword_list = stopwords.words('english')

In [46]:
porter = nltk.PorterStemmer()

In [47]:

# This function will take a string and lowercase it, remove punctuations and spaces, and then tokentize and stem those tokens
def normalize_review_text(text):
    text = text.lower()
    text = remove_punctuation(text)
    text = " ".join(text.split())
    text_tokens = tokenizer.tokenize(text)
    text_tokens = [porter.stem(w) for w in text_tokens if w not in stopword_list]
    return text_tokens

# Apply the function above to the text column
com["Text"] = com["Text"].apply(normalize_review_text)
com

,Id,PostId,Score,Text,CreationDate,UserDisplayName,UserId
0,38814080,24964538,0,"[php, file, get, sever, databas, result, array...",2014-07-26 10:45:07,NaN,2005071.0
1,38814081,24926353,0,"[alway, way, thing, depend, use, case, need, h...",2014-07-26 10:45:10,NaN,3787750.0
2,38814083,24969752,0,"[rohitvat, use, datagrid, data, entri, user, e...",2014-07-26 10:45:17,NaN,3008788.0
3,38814084,24969862,0,"[frederickcheung, it', simpl, thank, help, may...",2014-07-26 10:45:18,NaN,3493998.0
4,38814085,24970073,0,"[doh, miss, much, appreci, start, think, go, c...",2014-07-26 10:45:19,NaN,3839120.0
5,38814086,24969932,0,"[chang, i'm, tri]",2014-07-26 10:45:19,NaN,3794651.0
6,38814087,24957753,0,"[frank, thank, well, put, name, shader]",2014-07-26 10:45:30,NaN,1614697.0
7,38814090,24967270,0,"[interest, question, realli, program]",2014-07-26 10:45:52,NaN,545127.0
8,38814091,24969635,0,"[hors, name, next, time, i'll]",2014-07-26 10:46:00,user3814846,NaN
9,38814092,24970167,0,"[user, type, number, want, button, enabl, thre...",2014-07-26 10:46:02,NaN,3872762.0
10,38814093,24831034,0,"[could, pleas, show, code, crop, imag]",2014-07-26 10:46:05,NaN,2122991.0
11,38814095,24968975,0,"[laun, kinda, put, lie, fact, assign, loop, yo...",2014-07-26 10:46:29,NaN,157247.0
12,38814096,24970115,0,"[use, slidingmenu, librari, one, app, sinc, ne...",2014-07-26 10:46:30,NaN,1708743.0
13,38814097,24970131,0,"[need, get, 16, byte, display, string, via, co...",2014-07-26 10:46:33,NaN,2475484.0
14,38814098,24960941,0,"[thank, imag, seem, littl, stretch, found, fol...",2014-07-26 10:46:35,NaN,532462.0
15,38814099,24969969,0,"[get, typecast, error, see, edit, answer]",2014-07-26 10:46:38,NaN,3535925.0
16,38814100,24932294,0,"[harder, initi, thought, seem, don't, complet,...",2014-07-26 10:46:52,NaN,2904025.0
17,38814102,24969213,0,"[hand, tri, find, wich, code, defin, graph, na...",2014-07-26 10:46:53,NaN,3836391.0
18,38814103,24970177,0,"[tri, split, sure, look]",2014-07-26 10:46:58,NaN,892256.0
19,38814105,24969828,0,"[thank, answer, pleas, share, pseudocod, multi...",2014-07-26 10:47:03,NaN,3741831.0
20,38814107,24969888,0,"[writefil, createnewfil, imposs, find, path]",2014-07-26 10:47:06,NaN,3832184.0
21,38814108,24969890,0,"[want, style, name, adr, phone]",2014-07-26 10:47:08,NaN,2119788.0
22,38814109,24970070,0,"[user3777110, look, edit, answer, queri]",2014-07-26 10:47:12,NaN,998158.0
23,38814110,24969793,0,"[oh, wrong, like, okay, var, vc, alertvc, nibn...",2014-07-26 10:47:13,NaN,1550974.0
24,38814111,24970167,0,"[look, valid, event, 3, textbox]",2014-07-26 10:47:15,NaN,1197518.0
25,38814113,24926544,0,"[can't, directli, call, super, uinavigationcon...",2014-07-26 10:47:25,NaN,870671.0
26,38814114,24969858,0,"[thank, answer, solv, problem]",2014-07-26 10:47:31,NaN,3370495.0
27,38814115,24947581,1,"[first, normal, form, first, whole, seri, norm...",2014-07-26 10:47:34,NaN,19937.0
28,38814116,10243664,0,"[thank, work, 64bit, os]",2014-07-26 10:47:34,NaN,1084501.0
29,38814117,14993590,0,"[exactli, use, code, mbluetoothadapt, getprofi...",2014-07-26 10:47:34,NaN,747873.0
...,...,...,...,...,...,...,...
70,38814171,24969752,0,"[select, last, row, commit, row, press, enter,...",2014-07-26 10:51:15,NaN,632337.0
71,38814172,24969747,0,"[simonblanck, also, init, data, cannot, undefi...",2014-07-26 10:51:19,NaN,1558322.0
72,38814173,24969867,0,"[help, use, paramet, function, call, c, code]",2014-07-26 10:51:27,NaN,870561.0
73,38814174,24962509,0,"[db, last, insert, id, remov, drupal, 7, quest...",2014-07-26 10:51:29,NaN,830680.0
74,38814176,24970084,0,"[perfect, fiddler, http, jsfiddl, net, qjz2c]",2014-07-26 10:51:38,NaN,2081982.0
75,38814177,24970120,0,"[add, code, loginpanel, loginpanela]",2014-07-26 10:51:58,NaN,449946.0
76,38814178,24970214,2,"[blahzix, tentri, th32ownerprocessid, doesn't,...",2014-07-26 10:52:05,NaN,311966.0
77,38814179,24938182,0,"[sashka, sorri, excess, comment, clean, figur,...",2014-07-26 10:52:08,NaN,3280533.0
78,38814181,24969430,0,"[great, great, great, goe, good, remov, nstimer]",2014-07-26 10:52:13,NaN,1066828.0
79,38814183,24970141,1,[shouldn't],2014-07-26 10:52:17,NaN,848164.0
80,38814184,24970141,0,"[shouldn't, use, don't, need]",2014-07-26 10:52:24,NaN,663031.0
81,38814185,24970205,0,"[yeah, wrote, next, sentenc, one, quot, know, ...",2014-07-26 10:52:27,NaN,3212350.0
82,38814186,24935471,0,"[michaÃ«lazevedo, right, kpferrorusernametaken,...",2014-07-26 10:52:28,NaN,1523425.0
83,38814187,23124855,0,"[solv, remov, oracl, java, 8, sudo, aptitud, i...",2014-07-26 10:52:35,NaN,108742.0
84,38814188,24969505,2,"[1, good, updat]",2014-07-26 10:52:40,NaN,548225.0
85,38814190,24892276,0,"[partial, solut, work, need, know, extern, pro...",2014-07-26 10:52:55,NaN,3105535.0
86,38814192,24953011,0,"[shouldn't, alway, type, object, pattern, noti...",2014-07-26 10:52:57,NaN,1988185.0
87,38814193,24970099,0,"[tri, follow, rule, given, link, solv, issu]",2014-07-26 10:53:01,NaN,1632209.0
88,38814194,24969652,0,"[method, xmpprosterdidendpopul, work, appdeleg...",2014-07-26 10:53:06,NaN,3878774.0
89,38814195,24966966,0,"[exampl, http, bl, ock, org, mbostock, 3884955...",2014-07-26 10:53:08,NaN,1172002.0
90,38814196,18383746,0,"[cdhowi, pleas, correct, claim, br, br, fine, ...",2014-07-26 10:53:18,NaN,352734.0
91,38814197,24911830,0,"[great, thank, end, get, work, better, method]",2014-07-26 10:53:19,NaN,1874415.0
92,38814200,24968444,0,"[fix, use, adminid, yet, isnt, delet]",2014-07-26 10:53:29,NaN,3879052.0
93,38814202,156868,0,"[first, sentenc, isn't, true, use, expectedexc...",2014-07-26 10:53:36,NaN,1081110.0
94,38814203,24942333,0,"[excelnoobie25, user3879000, make, excel, poin...",2014-07-26 10:53:43,NaN,973283.0
95,38814205,24970199,0,"[move, statement, button, textbox', text, chan...",2014-07-26 10:54:01,NaN,3872762.0
96,38814207,24958789,0,"[sorri, carlosejimenez, yesterday, internet, c...",2014-07-26 10:54:02,NaN,3492813.0
97,38814209,24969134,1,"[could, post, help, http, stackoverflow, com, ...",2014-07-26 10:54:22,NaN,2967091.0
98,38814211,24945944,0,"[you'r, welcom, honest, don't, think, runtim, ...",2014-07-26 10:54:24,NaN,1166087.0
99,38814212,24961092,0,"[could, past, df, head, question]",2014-07-26 10:54:28,NaN,1082349.0

In [48]:
df = pd.DataFrame(data=com)

In [53]:
df

,Id,PostId,Score,Text,CreationDate,UserDisplayName,UserId
0,38814080,24964538,0,"[php, file, get, sever, databas, result, array...",2014-07-26 10:45:07,NaN,2005071.0
1,38814081,24926353,0,"[alway, way, thing, depend, use, case, need, h...",2014-07-26 10:45:10,NaN,3787750.0
2,38814083,24969752,0,"[rohitvat, use, datagrid, data, entri, user, e...",2014-07-26 10:45:17,NaN,3008788.0
3,38814084,24969862,0,"[frederickcheung, it', simpl, thank, help, may...",2014-07-26 10:45:18,NaN,3493998.0
4,38814085,24970073,0,"[doh, miss, much, appreci, start, think, go, c...",2014-07-26 10:45:19,NaN,3839120.0
5,38814086,24969932,0,"[chang, i'm, tri]",2014-07-26 10:45:19,NaN,3794651.0
6,38814087,24957753,0,"[frank, thank, well, put, name, shader]",2014-07-26 10:45:30,NaN,1614697.0
7,38814090,24967270,0,"[interest, question, realli, program]",2014-07-26 10:45:52,NaN,545127.0
8,38814091,24969635,0,"[hors, name, next, time, i'll]",2014-07-26 10:46:00,user3814846,NaN
9,38814092,24970167,0,"[user, type, number, want, button, enabl, thre...",2014-07-26 10:46:02,NaN,3872762.0
10,38814093,24831034,0,"[could, pleas, show, code, crop, imag]",2014-07-26 10:46:05,NaN,2122991.0
11,38814095,24968975,0,"[laun, kinda, put, lie, fact, assign, loop, yo...",2014-07-26 10:46:29,NaN,157247.0
12,38814096,24970115,0,"[use, slidingmenu, librari, one, app, sinc, ne...",2014-07-26 10:46:30,NaN,1708743.0
13,38814097,24970131,0,"[need, get, 16, byte, display, string, via, co...",2014-07-26 10:46:33,NaN,2475484.0
14,38814098,24960941,0,"[thank, imag, seem, littl, stretch, found, fol...",2014-07-26 10:46:35,NaN,532462.0
15,38814099,24969969,0,"[get, typecast, error, see, edit, answer]",2014-07-26 10:46:38,NaN,3535925.0
16,38814100,24932294,0,"[harder, initi, thought, seem, don't, complet,...",2014-07-26 10:46:52,NaN,2904025.0
17,38814102,24969213,0,"[hand, tri, find, wich, code, defin, graph, na...",2014-07-26 10:46:53,NaN,3836391.0
18,38814103,24970177,0,"[tri, split, sure, look]",2014-07-26 10:46:58,NaN,892256.0
19,38814105,24969828,0,"[thank, answer, pleas, share, pseudocod, multi...",2014-07-26 10:47:03,NaN,3741831.0
20,38814107,24969888,0,"[writefil, createnewfil, imposs, find, path]",2014-07-26 10:47:06,NaN,3832184.0
21,38814108,24969890,0,"[want, style, name, adr, phone]",2014-07-26 10:47:08,NaN,2119788.0
22,38814109,24970070,0,"[user3777110, look, edit, answer, queri]",2014-07-26 10:47:12,NaN,998158.0
23,38814110,24969793,0,"[oh, wrong, like, okay, var, vc, alertvc, nibn...",2014-07-26 10:47:13,NaN,1550974.0
24,38814111,24970167,0,"[look, valid, event, 3, textbox]",2014-07-26 10:47:15,NaN,1197518.0
25,38814113,24926544,0,"[can't, directli, call, super, uinavigationcon...",2014-07-26 10:47:25,NaN,870671.0
26,38814114,24969858,0,"[thank, answer, solv, problem]",2014-07-26 10:47:31,NaN,3370495.0
27,38814115,24947581,1,"[first, normal, form, first, whole, seri, norm...",2014-07-26 10:47:34,NaN,19937.0
28,38814116,10243664,0,"[thank, work, 64bit, os]",2014-07-26 10:47:34,NaN,1084501.0
29,38814117,14993590,0,"[exactli, use, code, mbluetoothadapt, getprofi...",2014-07-26 10:47:34,NaN,747873.0
...,...,...,...,...,...,...,...
70,38814171,24969752,0,"[select, last, row, commit, row, press, enter,...",2014-07-26 10:51:15,NaN,632337.0
71,38814172,24969747,0,"[simonblanck, also, init, data, cannot, undefi...",2014-07-26 10:51:19,NaN,1558322.0
72,38814173,24969867,0,"[help, use, paramet, function, call, c, code]",2014-07-26 10:51:27,NaN,870561.0
73,38814174,24962509,0,"[db, last, insert, id, remov, drupal, 7, quest...",2014-07-26 10:51:29,NaN,830680.0
74,38814176,24970084,0,"[perfect, fiddler, http, jsfiddl, net, qjz2c]",2014-07-26 10:51:38,NaN,2081982.0
75,38814177,24970120,0,"[add, code, loginpanel, loginpanela]",2014-07-26 10:51:58,NaN,449946.0
76,38814178,24970214,2,"[blahzix, tentri, th32ownerprocessid, doesn't,...",2014-07-26 10:52:05,NaN,311966.0
77,38814179,24938182,0,"[sashka, sorri, excess, comment, clean, figur,...",2014-07-26 10:52:08,NaN,3280533.0
78,38814181,24969430,0,"[great, great, great, goe, good, remov, nstimer]",2014-07-26 10:52:13,NaN,1066828.0
79,38814183,24970141,1,[shouldn't],2014-07-26 10:52:17,NaN,848164.0
80,38814184,24970141,0,"[shouldn't, use, don't, need]",2014-07-26 10:52:24,NaN,663031.0
81,38814185,24970205,0,"[yeah, wrote, next, sentenc, one, quot, know, ...",2014-07-26 10:52:27,NaN,3212350.0
82,38814186,24935471,0,"[michaÃ«lazevedo, right, kpferrorusernametaken,...",2014-07-26 10:52:28,NaN,1523425.0
83,38814187,23124855,0,"[solv, remov, oracl, java, 8, sudo, aptitud, i...",2014-07-26 10:52:35,NaN,108742.0
84,38814188,24969505,2,"[1, good, updat]",2014-07-26 10:52:40,NaN,548225.0
85,38814190,24892276,0,"[partial, solut, work, need, know, extern, pro...",2014-07-26 10:52:55,NaN,3105535.0
86,38814192,24953011,0,"[shouldn't, alway, type, object, pattern, noti...",2014-07-26 10:52:57,NaN,1988185.0
87,38814193,24970099,0,"[tri, follow, rule, given, link, solv, issu]",2014-07-26 10:53:01,NaN,1632209.0
88,38814194,24969652,0,"[method, xmpprosterdidendpopul, work, appdeleg...",2014-07-26 10:53:06,NaN,3878774.0
89,38814195,24966966,0,"[exampl, http, bl, ock, org, mbostock, 3884955...",2014-07-26 10:53:08,NaN,1172002.0
90,38814196,18383746,0,"[cdhowi, pleas, correct, claim, br, br, fine, ...",2014-07-26 10:53:18,NaN,352734.0
91,38814197,24911830,0,"[great, thank, end, get, work, better, method]",2014-07-26 10:53:19,NaN,1874415.0
92,38814200,24968444,0,"[fix, use, adminid, yet, isnt, delet]",2014-07-26 10:53:29,NaN,3879052.0
93,38814202,156868,0,"[first, sentenc, isn't, true, use, expectedexc...",2014-07-26 10:53:36,NaN,1081110.0
94,38814203,24942333,0,"[excelnoobie25, user3879000, make, excel, poin...",2014-07-26 10:53:43,NaN,973283.0
95,38814205,24970199,0,"[move, statement, button, textbox', text, chan...",2014-07-26 10:54:01,NaN,3872762.0
96,38814207,24958789,0,"[sorri, carlosejimenez, yesterday, internet, c...",2014-07-26 10:54:02,NaN,3492813.0
97,38814209,24969134,1,"[could, post, help, http, stackoverflow, com, ...",2014-07-26 10:54:22,NaN,2967091.0
98,38814211,24945944,0,"[you'r, welcom, honest, don't, think, runtim, ...",2014-07-26 10:54:24,NaN,1166087.0
99,38814212,24961092,0,"[could, past, df, head, question]",2014-07-26 10:54:28,NaN,1082349.0

In [54]:
def calculate_positivity(text):
    num_tokens = len(text)
    num_positive_tokens = 0
    for t in text:
        if t in positive_terms:
            num_positive_tokens = num_positive_tokens + 1
    # The positivity score is the fraction of tokens that were found in the positive dictionary
    return float(num_positive_tokens) / float(num_tokens)

df["positivity_score"] = df["Text"].apply(calculate_positivity)

def calculate_negativity(text):
    num_tokens = len(text)
    num_negative_tokens = 0
    for t in text:
        if t in negative_terms:
            num_negative_tokens = num_negative_tokens + 1
    # The positivity score is the fraction of tokens that were found in the positive dictionary
    return float(num_negative_tokens) / float(num_tokens)

df["negativity_score"] = df["Text"].apply(calculate_negativity)
df

,Id,PostId,Score,Text,CreationDate,UserDisplayName,UserId,positivity_score,negativity_score
0,38814080,24964538,0,"[php, file, get, sever, databas, result, array...",2014-07-26 10:45:07,NaN,2005071.0,0.000000,0.000000
1,38814081,24926353,0,"[alway, way, thing, depend, use, case, need, h...",2014-07-26 10:45:10,NaN,3787750.0,0.066667,0.000000
2,38814083,24969752,0,"[rohitvat, use, datagrid, data, entri, user, e...",2014-07-26 10:45:17,NaN,3008788.0,0.000000,0.000000
3,38814084,24969862,0,"[frederickcheung, it', simpl, thank, help, may...",2014-07-26 10:45:18,NaN,3493998.0,0.083333,0.000000
4,38814085,24970073,0,"[doh, miss, much, appreci, start, think, go, c...",2014-07-26 10:45:19,NaN,3839120.0,0.000000,0.125000
5,38814086,24969932,0,"[chang, i'm, tri]",2014-07-26 10:45:19,NaN,3794651.0,0.000000,0.000000
6,38814087,24957753,0,"[frank, thank, well, put, name, shader]",2014-07-26 10:45:30,NaN,1614697.0,0.333333,0.000000
7,38814090,24967270,0,"[interest, question, realli, program]",2014-07-26 10:45:52,NaN,545127.0,0.250000,0.000000
8,38814091,24969635,0,"[hors, name, next, time, i'll]",2014-07-26 10:46:00,user3814846,NaN,0.000000,0.000000
9,38814092,24970167,0,"[user, type, number, want, button, enabl, thre...",2014-07-26 10:46:02,NaN,3872762.0,0.000000,0.000000
10,38814093,24831034,0,"[could, pleas, show, code, crop, imag]",2014-07-26 10:46:05,NaN,2122991.0,0.000000,0.000000
11,38814095,24968975,0,"[laun, kinda, put, lie, fact, assign, loop, yo...",2014-07-26 10:46:29,NaN,157247.0,0.000000,0.000000
12,38814096,24970115,0,"[use, slidingmenu, librari, one, app, sinc, ne...",2014-07-26 10:46:30,NaN,1708743.0,0.090909,0.000000
13,38814097,24970131,0,"[need, get, 16, byte, display, string, via, co...",2014-07-26 10:46:33,NaN,2475484.0,0.000000,0.000000
14,38814098,24960941,0,"[thank, imag, seem, littl, stretch, found, fol...",2014-07-26 10:46:35,NaN,532462.0,0.210526,0.000000
15,38814099,24969969,0,"[get, typecast, error, see, edit, answer]",2014-07-26 10:46:38,NaN,3535925.0,0.000000,0.000000
16,38814100,24932294,0,"[harder, initi, thought, seem, don't, complet,...",2014-07-26 10:46:52,NaN,2904025.0,0.066667,0.000000
17,38814102,24969213,0,"[hand, tri, find, wich, code, defin, graph, na...",2014-07-26 10:46:53,NaN,3836391.0,0.000000,0.000000
18,38814103,24970177,0,"[tri, split, sure, look]",2014-07-26 10:46:58,NaN,892256.0,0.250000,0.000000
19,38814105,24969828,0,"[thank, answer, pleas, share, pseudocod, multi...",2014-07-26 10:47:03,NaN,3741831.0,0.285714,0.000000
20,38814107,24969888,0,"[writefil, createnewfil, imposs, find, path]",2014-07-26 10:47:06,NaN,3832184.0,0.000000,0.000000
21,38814108,24969890,0,"[want, style, name, adr, phone]",2014-07-26 10:47:08,NaN,2119788.0,0.000000,0.000000
22,38814109,24970070,0,"[user3777110, look, edit, answer, queri]",2014-07-26 10:47:12,NaN,998158.0,0.000000,0.000000
23,38814110,24969793,0,"[oh, wrong, like, okay, var, vc, alertvc, nibn...",2014-07-26 10:47:13,NaN,1550974.0,0.142857,0.047619
24,38814111,24970167,0,"[look, valid, event, 3, textbox]",2014-07-26 10:47:15,NaN,1197518.0,0.000000,0.000000
25,38814113,24926544,0,"[can't, directli, call, super, uinavigationcon...",2014-07-26 10:47:25,NaN,870671.0,0.062500,0.000000
26,38814114,24969858,0,"[thank, answer, solv, problem]",2014-07-26 10:47:31,NaN,3370495.0,0.250000,0.250000
27,38814115,24947581,1,"[first, normal, form, first, whole, seri, norm...",2014-07-26 10:47:34,NaN,19937.0,0.026316,0.000000
28,38814116,10243664,0,"[thank, work, 64bit, os]",2014-07-26 10:47:34,NaN,1084501.0,0.250000,0.000000
29,38814117,14993590,0,"[exactli, use, code, mbluetoothadapt, getprofi...",2014-07-26 10:47:34,NaN,747873.0,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...
70,38814171,24969752,0,"[select, last, row, commit, row, press, enter,...",2014-07-26 10:51:15,NaN,632337.0,0.000000,0.000000
71,38814172,24969747,0,"[simonblanck, also, init, data, cannot, undefi...",2014-07-26 10:51:19,NaN,1558322.0,0.090909,0.000000
72,38814173,24969867,0,"[help, use, paramet, function, call, c, code]",2014-07-26 10:51:27,NaN,870561.0,0.000000,0.000000
73,38814174,24962509,0,"[db, last, insert, id, remov, drupal, 7, quest...",2014-07-26 10:51:29,NaN,830680.0,0.058824,0.058824
74,38814176,24970084,0,"[perfect, fiddler, http, jsfiddl, net, qjz2c]",2014-07-26 10:51:38,NaN,2081982.0,0.166667,0.000000
75,38814177,24970120,0,"[add, code, loginpanel, loginpanela]",2014-07-26 10:51:58,NaN,449946.0,0.000000,0.000000
76,38814178,24970214,2,"[blahzix, tentri, th32ownerprocessid, doesn't,...",2014-07-26 10:52:05,NaN,311966.0,0.000000,0.000000
77,38814179,24938182,0,"[sashka, sorri, excess, comment, clean, figur,...",2014-07-26 10:52:08,NaN,3280533.0,0.000000,0.000000
78,38814181,24969430,0,"[great, great, great, goe, good, remov, nstimer]",2014-07-26 10:52:13,NaN,1066828.0,0.571429,0.000000
79,38814183,24970141,1,[shouldn't],2014-07-26 10:52:17,NaN,848164.0,0.000000,0.000000
80,38814184,24970141,0,"[shouldn't, use, don't, need]",2014-07-26 10:52:24,NaN,663031.0,0.000000,0.000000
81,38814185,24970205,0,"[yeah, wrote, next, sentenc, one, quot, know, ...",2014-07-26 10:52:27,NaN,3212350.0,0.000000,0.111111
82,38814186,24935471,0,"[michaÃ«lazevedo, right, kpferrorusernametaken,...",2014-07-26 10:52:28,NaN,1523425.0,0.000000,0.000000
83,38814187,23124855,0,"[solv, remov, oracl, java, 8, sudo, aptitud, i...",2014-07-26 10:52:35,NaN,108742.0,0.000000,0.000000
84,38814188,24969505,2,"[1, good, updat]",2014-07-26 10:52:40,NaN,548225.0,0.333333,0.000000
85,38814190,24892276,0,"[partial, solut, work, need, know, extern, pro...",2014-07-26 10:52:55,NaN,3105535.0,0.000000,0.000000
86,38814192,24953011,0,"[shouldn't, alway, type, object, pattern, noti...",2014-07-26 10:52:57,NaN,1988185.0,0.000000,0.000000
87,38814193,24970099,0,"[tri, follow, rule, given, link, solv, issu]",2014-07-26 10:53:01,NaN,1632209.0,0.000000,0.000000
88,38814194,24969652,0,"[method, xmpprosterdidendpopul, work, appdeleg...",2014-07-26 10:53:06,NaN,3878774.0,0.000000,0.000000
89,38814195,24966966,0,"[exampl, http, bl, ock, org, mbostock, 3884955...",2014-07-26 10:53:08,NaN,1172002.0,0.000000,0.000000
90,38814196,18383746,0,"[cdhowi, pleas, correct, claim, br, br, fine, ...",2014-07-26 10:53:18,NaN,352734.0,0.050000,0.050000
91,38814197,24911830,0,"[great, thank, end, get, work, better, method]",2014-07-26 10:53:19,NaN,1874415.0,0.428571,0.000000
92,38814200,24968444,0,"[fix, use, adminid, yet, isnt, delet]",2014-07-26 10:53:29,NaN,3879052.0,0.000000,0.000000
93,38814202,156868,0,"[first, sentenc, isn't, true, use, expectedexc...",2014-07-26 10:53:36,NaN,1081110.0,0.040000,0.040000
94,38814203,24942333,0,"[excelnoobie25, user3879000, make, excel, poin...",2014-07-26 10:53:43,NaN,973283.0,0.021277,0.021277
95,38814205,24970199,0,"[move, statement, button, textbox', text, chan...",2014-07-26 10:54:01,NaN,3872762.0,0.000000,0.000000
96,38814207,24958789,0,"[sorri, carlosejimenez, yesterday, internet, c...",2014-07-26 10:54:02,NaN,3492813.0,0.000000,0.033333
97,38814209,24969134,1,"[could, post, help, http, stackoverflow, com, ...",2014-07-26 10:54:22,NaN,2967091.0,0.000000,0.000000
98,38814211,24945944,0,"[you'r, welcom, honest, don't, think, runtim, ...",2014-07-26 10:54:24,NaN,1166087.0,0.046512,0.023256
99,38814212,24961092,0,"[could, past, df, head, question]",2014-07-26 10:54:28,NaN,1082349.0,0.000000,0.000000

In [58]:
df.to_csv('df_com.csv')