In [2]:
import nltk
import pandas as pd
print(nltk.__version__)
%pwd

3.2.5

'/Users/xinyun/Desktop/INST737/Final_Project'

In [12]:
data = pd.read_csv('data1112_no_html.csv', encoding="utf-8")
data.head

/Users/xinyun/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

<bound method NDFrame.head of          PostId  X         PostCreation  PostDeletion  postScore  \
0      34552551  1  2016-01-01 00:00:07           NaN          1
1      34552552  1  2016-01-01 00:00:39           NaN          2
2      34552558  1  2016-01-01 00:01:27           NaN          1
3      34552560  1  2016-01-01 00:01:50           NaN          0
4      34552610  1  2016-01-01 00:12:53           NaN         -1
5      34552625  1  2016-01-01 00:16:26           NaN          1
6      34552653  1  2016-01-01 00:21:42           NaN          0
7      34552554  1  2016-01-01 00:00:50           NaN          0
8      34552557  1  2016-01-01 00:01:12           NaN          1
9      34552565  1  2016-01-01 00:02:53           NaN          2
10     34552587  1  2016-01-01 00:08:12           NaN          0
11     34552615  1  2016-01-01 00:13:52           NaN          0
12     34552555  1  2016-01-01 00:00:51           NaN         -1
13     34552563  1  2016-01-01 00:02:22           NaN          2
14     34552589  1  2016-01-01 00:08:22           NaN          0
15     34552661  1  2016-01-01 00:23:40           NaN          0
16     34552711  1  2016-01-01 00:36:29           NaN          0
17     34552719  1  2016-01-01 00:39:36           NaN          0
18     34552733  1  2016-01-01 00:42:07           NaN          1
19     34552584  1  2016-01-01 00:07:19           NaN          1
20     34552603  1  2016-01-01 00:11:37           NaN          0
21     34552612  1  2016-01-01 00:13:10           NaN          0
22     34552614  1  2016-01-01 00:13:26           NaN         -1
23     34552623  1  2016-01-01 00:15:55           NaN          4
24     34552550  1  2016-01-01 00:00:03           NaN          0
25     34552567  1  2016-01-01 00:03:46           NaN          3
26     34552593  1  2016-01-01 00:10:06           NaN          0
27     34552600  1  2016-01-01 00:11:01           NaN          1
28     34552642  1  2016-01-01 00:19:19           NaN          1
29     34552629  1  2016-01-01 00:17:17           NaN          1
...         ... ..                  ...           ...        ...
49970  34706961  1  2016-01-10 15:08:07           NaN          1
49971  34706972  1  2016-01-10 15:08:49           NaN          2
49972  34707012  1  2016-01-10 15:13:44           NaN          0
49973  34707021  1  2016-01-10 15:14:26           NaN          2
49974  34707035  1  2016-01-10 15:15:50           NaN          0
49975  34707037  1  2016-01-10 15:15:58           NaN          0
49976  34707060  1  2016-01-10 15:17:44           NaN          0
49977  34707070  1  2016-01-10 15:18:57           NaN          0
49978  34707071  1  2016-01-10 15:19:02           NaN         -3
49979  34707079  1  2016-01-10 15:20:20           NaN          0
49980  34707139  1  2016-01-10 15:25:22           NaN          0
49981  34707153  1  2016-01-10 15:26:17           NaN          0
49982  34707164  1  2016-01-10 15:27:25           NaN          2
49983  34707178  1  2016-01-10 15:28:57           NaN          1
49984  34707187  1  2016-01-10 15:29:51           NaN          2
49985  34707194  1  2016-01-10 15:30:15           NaN         -2
49986  34707197  1  2016-01-10 15:30:23           NaN          0
49987  34707203  1  2016-01-10 15:30:53           NaN          1
49988  34707219  1  2016-01-10 15:32:09           NaN          0
49989  34707220  1  2016-01-10 15:32:23           NaN         -1
49990  34707222  1  2016-01-10 15:32:25           NaN          0
49991  34707236  1  2016-01-10 15:33:22           NaN          1
49992  34707264  1  2016-01-10 15:35:28           NaN          1
49993  34707282  1  2016-01-10 15:37:29           NaN          0
49994  34707342  1  2016-01-10 15:42:18           NaN          1
49995  34707383  1  2016-01-10 15:45:50           NaN          2
49996  34707385  1  2016-01-10 15:45:52           NaN          0
49997  34707280  1  2016-01-10 15:37:10           NaN          8
49998  34707380  1  2016-01-10 15:45:41           NaN          0
49999  34707980  1  2016-01-10 12:50:01           NaN          1

       postViewcount                                               body  \
0                213  <p>Hello I am new to Rails.</p>\r\n\r\n<p>Here...
1               2169  <p>everyone. </p>\r\n\r\n<p>Main question: I a...
2                237  <p><strong>What is it about ?</strong></p>\r\n...
3                 39  <p>I just want to know which of this two struc...
4                311  <p>I'm using this echo statement in a php scri...
5               3246  <p>In the DynamoDB documentation and in many p...
6               2273  <p>I am on a Raspberry Pi, and I am using a pr...
7                237  <p>Ever since I updated android studio to the ...
8                 28  <p>I've been trying to set up Forem (a Rails 4...
9                592  <p>Please read the question before marking thi...
10               139  <p>I have a Mac with OS 10.11.1, from which I ...
11               163  <p>I'm creating custom functions for sign up a...
12                61  <p>I am creating some Java codes like the foll...
13               942  <p>I'm using the PHP build system <code>phing<...
14               575  <p>I have review many examples but have not be...
15                25  <p>I have a table that shows a list of prescri...
16                49  <p>In my model I'm receiving a property that's...
17               171  <p>I'm writing an iOS app that has two views. ...
18               779  <p>I loaded content with divs dynamically via ...
19               339  <p>Happy new year to all of you!\r\nI trained ...
20                61  <p>I have a imageview that randomly generate 1...
21                42  <p>I am making an app that tells you how much ...
22               123  <p>Once a Project is uploaded/Created in Proje...
23               673  <p>So I'm watching tutorials on Code School, a...
24               131  <p>Another newbie question. I am trying to und...
25              1373  <p>When the timepicker control is inside a for...
26                78  <p>I have embedded a youtube video as shown <a...
27                44  <p>I just got a basic Node.js site up and runn...
28               151  <p><code>Orders</code> is 350k rows. <code>Use...
29               715  <p>I currently have a test suite using Nunit a...
...              ...                                                ...
49970            542  <p>CodePen link: <a href="http://codepen.io/mr...
49971            245  <p>How can I just simple install apache2 packa...
49972             32  <p>We are currently in process of development ...
49973            385  <p>I am trying to compare a <code>combobox</co...
49974            108  <p>I am trying to change the font in a WPF Ric...
49975             58  <p>There is certain part of the code in my pro...
49976            360  <p>Hi I'm using this following python parser t...
49977             56  <p>Been spending too much time on this.."f$%"\...
49978             75  <p>I have the following piece of code as a pro...
49979            206  <p>I want to show website preview on a link si...
49980             32  <p>I am working on a project in Java that invo...
49981            483  <p>I <a href="https://stackoverflow.com/questi...
49982             43  <p>I am a beginner in Angular and Rest and I h...
49983             81  <p>Have a String given by:</p>\r\n\r\n<p>_xdyj...
49984          38685  <p>I'm looking for simple bullet point answers...
49985             61  <p>My table has 90 columns.</p>\r\n\r\n<p>How ...
49986             44  <p>using Python3.5\r\ni have two lists of stri...
49987           1465  <p>I want to stringify a large object (to writ...
49988             12  <p>I am concerned this may not be possible (at...
49989            216  <p>I have started to use swashbuckle for my re...
49990             70  <p>I have created such statement: </p>\r\n\r\n...
49991             92  <p>I have to read a text file using this struc...
49992            885  <p>I'm trying to get ADC with DMA working on m...
49993             28  <p>How can i calculate and print the result in...
49994            444  <p>I have a table with a column configured as ...
49995            128  <p>I was trying to select a element using prot...
49996             50  <p>i have this code:</p>\r\n\r\n<pre><code>pub...
49997            625  <p>Let's say I have this dictionary:</p>\r\n\r...
49998            376  <p>I'm writting an Android App and connect to ...
49999            145  <p>I have got a problem on my blog. I installe...

                                                   title  \
0      Rails - Unknown Attribute - Unable to add a ne...
1      Selenium Firefox webdriver won't load a blank ...
2      Force delete Session records for the current l...
3                    Which data structure (full HABTM ?)
4              Adding ternary operator in echo statement
5      How to get sub 10ms response times from AWS Dy...
6                   Execute terminal commands in python3
7                        Android Studio styles.xml Error
8      How to namespace routes in Rails 4 to set up F...
9      Is there a way to use flashlight on in Android...
10                       Using gnuplot remotely from Mac
11     Programatically adding product to magento cart...
12     Java: reference to non-finial local variables ...
13                   PHP: Phing, Phar, and phar.readonly
14     mvc partial view autocomplete using modal jque...
15     Rails - Trying to check if a column is empty b...
16     Converting an int into a set of columns with R...
17                  Two RCTRootView instances in one app
18     addEventListener not working for ajax generate...
19     Is there any chance I got memory leak with pyt...
20      If statement depending on the random image shown
21           How do I impliment [example.text intValue]?
22     How to Copy Projects in Project Web App for Of...
23     HTML/CSS - How to get label inside form to ani...
24                                 Scope between methods
25     How to get ui.bootstrap timepicker control to ...
26     Java Swing: focus JWebBrowser and press space ...
27               Can't style body in style.css (Node.js)
28     Joining on table-valued function slows down query
29     Run adiitional cleanup function on test failur...
...                                                  ...
49970  The collapsed navigation bar button is not exp...
49971                  simple shell inline provisionning
49972                         Web server choice for SSJS
49973  How to compare a combo box value with a table ...
49974      How do I change the font in a WPF RichTextBox
49975                                  Formatting in cpp
49976           HTMLParser python turn data into string?
49977                      flat XML to nested using XSLT
49978                        List append comes out wrong
49979  a website preview - loading a webpage using ja...
49980             javascript library in my Java project?
49981  Don't reload the ngView template when I change...
49982  'Anonymous user' error after passing data with...
49983                            Regular Expression Java
49984  What are some advantages and disadvantages for...
49985  How do I determine which column has been updated?
49986                  "multiplying" two list of strings
49987  How to use JSONStream to stringify a large object
49988  magento 1.4 - have different subdomain route t...
49989         Swashbuckle returns nullreferenceexception
49990      executeUpdate() does not add string variables
49991      Structure as a parameter of extern function C
49992                 STM32F4 ADC DMA config not working
49993       Sum Multiple Text and Create New Column in R
49994        PLSQL - convert UTF-8 NVARCHAR2 to VARCHAR2
49995      protractor Unexpected identifier for selector
49996  LINQ Convert var collection to a specific coll...
49997            Selecting random values from dictionary
49998   Connect Azure service bus on Android by Rest API
49999  Recommended post slide out post widget not wor...

                                                    tags  numAnswer  \
0                                <ruby><ruby-on-rails-4>          2
1        <python><firefox><selenium><selenium-webdriver>          1
2                    <laravel><laravel-5.1><laravel-5.2>          1
3      <data-structures><has-and-belongs-to-many><has...          1
4                                                  <php>          3
5                 <amazon-web-services><amazon-dynamodb>          3
6      <python><python-3.x><raspberry-pi><subprocess>...          1
7                              <android><android-studio>          2
8        <ruby-on-rails><ruby-on-rails-4><routes><forem>          1
9      <java><android><android-camera><flashlight><im...          2
10                                        <osx><gnuplot>          0
11                                             <magento>          1
12               <java><multithreading><local-variables>          2
13                                    <php><phing><phar>          1
14                             <c#><jquery><asp.net-mvc>          1
15                  <ruby-on-rails-4><ruby-on-rails-3.2>          1
16                                    <c#><razor><flags>          1
17                                   <ios><react-native>          1
18                                    <javascript><ajax>          1
19     <python><memory-management><memory-leaks><theano>          0
20                                     <android><random>          1
21                                   <ios><xcode><swift>          1
22                      <project><office365><ms-project>          1
23                                           <html><css>          1
24                                  <objective-c><scope>          1
25     <angularjs><twitter-bootstrap><angular-ui-boot...          0
26     <java><swing><youtube><djnativeswing><jwebbrow...          0
27             <html><css><node.js><express><mean-stack>          1
28                 <sql-server-2008><sql-execution-plan>          1
29           <c#><unit-testing><selenium><nunit><assert>          1
...                                                  ...        ...
49970                                <twitter-bootstrap>          1
49971                          <ubuntu><vagrant><packer>          1
49972                   <javascript><node.js><web><ssjs>          0
49973                          <sql><sql-server><vb.net>          2
49974                                      <wpf><vb.net>          1
49975                           <c++><c++11><formatting>          1
49976                              <python><html-parser>          2
49977                     <xml><xslt-2.0><xslt-grouping>          2
49978                                           <python>          2
49979                  <javascript><c#><jquery><asp.net>          1
49980                                 <javascript><java>          1
49981                               <angularjs><ngroute>          1
49982                          <angularjs><django><rest>          1
49983                                      <java><regex>          2
49984         <javascript><html><html5><save><embedding>          2
49985                                       <sql-server>          2
49986                      <python><list><concatenation>          0
49987                            <json><node.js><stream>          1
49988                             <php><apache><magento>          2
49989                         <asp.net-web-api><swagger>          1
49990                                   <java><database>          2
49991                   <c><function><structure><extern>          2
49992                               <c><stm32><dma><adc>          1
49993                                                <r>          1
49994                                     <utf-8><plsql>          1
49995          <javascript><automated-tests><protractor>          1
49996                            <c#><linq><collections>          1
49997                       <python><dictionary><random>          3
49998                             <java><android><azure>          1
49999                    <javascript><blogger><blogspot>          0

                             ...                          Favorite  \
0                            ...                               NaN
1                            ...                               1.0
2                            ...                               0.0
3                            ...                               NaN
4                            ...                               NaN
5                            ...                               NaN
6                            ...                               1.0
7                            ...                               NaN
8                            ...                               NaN
9                            ...                               NaN
10                           ...                               NaN
11                           ...                               NaN
12                           ...                               NaN
13                           ...                               NaN
14                           ...                               NaN
15                           ...                               NaN
16                           ...                               NaN
17                           ...                               NaN
18                           ...                               NaN
19                           ...                               NaN
20                           ...                               NaN
21                           ...                               NaN
22                           ...                               NaN
23                           ...                               1.0
24                           ...                               NaN
25                           ...                               NaN
26                           ...                               NaN
27                           ...                               NaN
28                           ...                               NaN
29                           ...                               NaN
...                          ...                               ...
49970                        ...                               NaN
49971                        ...                               NaN
49972                        ...                               NaN
49973                        ...                               NaN
49974                        ...                               NaN
49975                        ...                               NaN
49976                        ...                               NaN
49977                        ...                               NaN
49978                        ...                               NaN
49979                        ...                               NaN
49980                        ...                               NaN
49981                        ...                               NaN
49982                        ...                               NaN
49983                        ...                               NaN
49984                        ...                               1.0
49985                        ...                               NaN
49986                        ...                               NaN
49987                        ...                               NaN
49988                        ...                               NaN
49989                        ...                               NaN
49990                        ...                               NaN
49991                        ...                               NaN
49992                        ...                               NaN

In [13]:
data.shape

(50000, 21)

In [14]:
positive_terms = []
f = open('positive_terms.txt', "r")
positive_terms = f.read().splitlines()
f.close()

negative_terms = []
f = open('negative_terms.txt', "r")
negative_terms = f.read().splitlines()
f.close()

In [15]:
#remove punctuation
import string

def remove_punctuation(text):
    # Grab the list of standard punctuation symbols that are provided in the string library
    punctuations = string.punctuation # includes following characters: !"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~

    # But don't strip out apostrophes, as we want to preserve possessives and contractions, an alternative would be to expand contractions
    excluded_punctuations = ["'"]
    for p in punctuations:
        if p not in excluded_punctuations:
            # replace each punctuation symbol by a space
            text = text.replace(p, " ") 

    return text

In [16]:
from nltk.tokenize import WhitespaceTokenizer

# Create a tokenizer from NLTK which will create tokens based on the whitespace in between words
tokenizer = WhitespaceTokenizer()

from nltk.corpus import stopwords
stopword_list = stopwords.words('english')

porter = nltk.PorterStemmer()

In [17]:
# This function will take a string and lowercase it, remove punctuations and spaces, and then tokentize and stem those tokens
def normalize_review_text(text):
    text = text.lower()
    text = remove_punctuation(text)
    text = " ".join(text.split())
    text_tokens = tokenizer.tokenize(text)
    text_tokens = [porter.stem(w) for w in text_tokens if w not in stopword_list]
    return text_tokens

# Apply the function above to the text column
data["Body_text"] = data["Body_text"].apply(normalize_review_text)
data

,PostId,X,PostCreation,PostDeletion,postScore,postViewcount,body,title,tags,numAnswer,...,Favorite,communityOwned,AcceptedAnswerId,max_ans_score,avg_ans_score,AnswererReputation,answererProfileViews,answererRegistration,X.1,Body_text
0,34552551,1,2016-01-01 00:00:07,NaN,1,213,<p>Hello I am new to Rails.</p>\r\n\r\n<p>Here...,Rails - Unknown Attribute - Unable to add a ne...,<ruby><ruby-on-rails-4>,2,...,NaN,NaN,34554360.0,1.0,0.0,6791.0,682.0,2015-12-06 15:27:33,2017-11-12 15:58:51,"[hello, new, rail, control, project, control, ..."
1,34552552,1,2016-01-01 00:00:39,NaN,2,2169,<p>everyone. </p>\r\n\r\n<p>Main question: I a...,Selenium Firefox webdriver won't load a blank ...,<python><firefox><selenium><selenium-webdriver>,1,...,1.0,NaN,34555040.0,2.0,2.0,106.0,3.0,2013-10-07 07:47:41,2017-11-12 15:58:51,"[everyon, main, question, use, python, api, se..."
2,34552558,1,2016-01-01 00:01:27,NaN,1,237,<p><strong>What is it about ?</strong></p>\r\n...,Force delete Session records for the current l...,<laravel><laravel-5.1><laravel-5.2>,1,...,0.0,NaN,NaN,0.0,0.0,2060.0,2698.0,2010-02-15 13:10:04,2017-11-12 15:58:51,"[use, session, tabl, keep, accumul, current, u..."
3,34552560,1,2016-01-01 00:01:50,NaN,0,39,<p>I just want to know which of this two struc...,Which data structure (full HABTM ?),<data-structures><has-and-belongs-to-many><has...,1,...,NaN,NaN,34552698.0,0.0,0.0,11.0,5.0,2014-04-16 09:02:57,2017-11-12 15:58:51,"[want, know, two, structur, best, better, perf..."
4,34552610,1,2016-01-01 00:12:53,NaN,-1,311,<p>I'm using this echo statement in a php scri...,Adding ternary operator in echo statement,<php>,3,...,NaN,NaN,34552768.0,1.0,1.0,133096.0,14559.0,2015-12-27 21:21:41,2017-11-12 15:58:51,"[i'm, use, echo, statement, php, script, work,..."
5,34552625,1,2016-01-01 00:16:26,NaN,1,3246,<p>In the DynamoDB documentation and in many p...,How to get sub 10ms response times from AWS Dy...,<amazon-web-services><amazon-dynamodb>,3,...,NaN,NaN,34557194.0,8.0,4.0,2750.0,105.0,2017-01-27 19:38:43,2017-11-12 15:58:51,"[dynamodb, document, mani, place, around, inte..."
6,34552653,1,2016-01-01 00:21:42,NaN,0,2273,"<p>I am on a Raspberry Pi, and I am using a pr...",Execute terminal commands in python3,<python><python-3.x><raspberry-pi><subprocess>...,1,...,1.0,NaN,34552734.0,5.0,5.0,1042.0,194.0,2014-12-26 23:50:53,2017-11-12 15:58:51,"[raspberri, pi, use, program, call, fswebcam, ..."
7,34552554,1,2016-01-01 00:00:50,NaN,0,237,<p>Ever since I updated android studio to the ...,Android Studio styles.xml Error,<android><android-studio>,2,...,NaN,NaN,NaN,0.0,0.0,1287.0,204.0,2015-12-16 21:48:30,2017-11-12 15:58:51,"[ever, sinc, updat, android, studio, newest, v..."
8,34552557,1,2016-01-01 00:01:12,NaN,1,28,<p>I've been trying to set up Forem (a Rails 4...,How to namespace routes in Rails 4 to set up F...,<ruby-on-rails><ruby-on-rails-4><routes><forem>,1,...,NaN,NaN,NaN,1.0,1.0,117.0,20.0,2010-11-13 21:10:13,2017-11-12 15:58:51,"[i'v, tri, set, forem, rail, 4, forum, engin, ..."
9,34552565,1,2016-01-01 00:02:53,NaN,2,592,<p>Please read the question before marking thi...,Is there a way to use flashlight on in Android...,<java><android><android-camera><flashlight><im...,2,...,NaN,NaN,NaN,1.0,0.0,31360.0,4723.0,2011-10-06 12:34:46,2017-11-12 15:58:51,"[pleas, read, question, mark, duplic, i'm, tri..."
10,34552587,1,2016-01-01 00:08:12,NaN,0,139,"<p>I have a Mac with OS 10.11.1, from which I ...",Using gnuplot remotely from Mac,<osx><gnuplot>,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[mac, os, 10, 11, 1, ssh, use, termin, option,..."
11,34552615,1,2016-01-01 00:13:52,NaN,0,163,<p>I'm creating custom functions for sign up a...,Programatically adding product to magento cart...,<magento>,1,...,NaN,NaN,34562412.0,0.0,0.0,351.0,38.0,2012-01-30 13:05:18,2017-11-12 15:58:51,"[i'm, creat, custom, function, sign, ad, produ..."
12,34552555,1,2016-01-01 00:00:51,NaN,-1,61,<p>I am creating some Java codes like the foll...,Java: reference to non-finial local variables ...,<java><multithreading><local-variables>,2,...,NaN,NaN,NaN,1.0,0.0,64835.0,10832.0,2011-11-04 14:46:54,2017-11-12 15:58:51,"[creat, java, code, like, follow, new, thread,..."
13,34552563,1,2016-01-01 00:02:22,NaN,2,942,<p>I'm using the PHP build system <code>phing<...,"PHP: Phing, Phar, and phar.readonly",<php><phing><phar>,1,...,NaN,NaN,NaN,5.0,5.0,51.0,2.0,2016-01-31 23:11:43,2017-11-12 15:58:51,"[i'm, use, php, build, system, phing, creat, p..."
14,34552589,1,2016-01-01 00:08:22,NaN,0,575,<p>I have review many examples but have not be...,mvc partial view autocomplete using modal jque...,<c#><jquery><asp.net-mvc>,1,...,NaN,NaN,NaN,0.0,0.0,120911.0,6341.0,2008-11-25 05:29:48,2017-11-12 15:58:51,"[review, mani, exampl, abl, find, exampl, help..."
15,34552661,1,2016-01-01 00:23:40,NaN,0,25,<p>I have a table that shows a list of prescri...,Rails - Trying to check if a column is empty b...,<ruby-on-rails-4><ruby-on-rails-3.2>,1,...,NaN,NaN,34552771.0,0.0,0.0,2449.0,135.0,2014-06-24 22:07:53,2017-11-12 15:58:51,"[tabl, show, list, prescript, want, filter, pr..."
16,34552711,1,2016-01-01 00:36:29,NaN,0,49,<p>In my model I'm receiving a property that's...,Converting an int into a set of columns with R...,<c#><razor><flags>,1,...,NaN,NaN,34553592.0,1.0,1.0,2149.0,144.0,2012-10-27 01:27:34,2017-11-12 15:58:51,"[model, i'm, receiv, properti, that', integ, c..."
17,34552719,1,2016-01-01 00:39:36,NaN,0,171,<p>I'm writing an iOS app that has two views. ...,Two RCTRootView instances in one app,<ios><react-native>,1,...,NaN,NaN,34559063.0,0.0,0.0,743.0,76.0,2012-09-27 00:17:03,2017-11-12 15:58:51,"[i'm, write, io, app, two, view, view, rctroot..."
18,34552733,1,2016-01-01 00:42:07,NaN,1,779,<p>I loaded content with divs dynamically via ...,addEventListener not working for ajax generate...,<javascript><ajax>,1,...,NaN,NaN,NaN,0.0,0.0,781.0,475.0,2015-08-09 14:41:32,2017-11-12 15:58:51,"[load, content, div, dynam, via, ajax, pure, j..."
19,34552584,1,2016-01-01 00:07:19,NaN,1,339,<p>Happy new year to all of you!\r\nI trained ...,Is there any chance I got memory leak with pyt...,<python><memory-management><memory-leaks><theano>,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[happi, new, year, train, deep, learn, model, ..."
20,34552603,1,2016-01-01 00:11:37,NaN,0,61,<p>I have a imageview that randomly generate 1...,If statement depending on the random image shown,<android><random>,1,...,NaN,NaN,34553435.0,0.0,0.0,1794.0,117.0,2013-09-21 02:51:49,2017-11-12 15:58:51,"[imageview, randomli, gener, 1, 2, possibl, im..."
21,34552612,1,2016-01-01 00:13:10,NaN,0,42,<p>I am making an app that tells you how much ...,How do I impliment [example.text intValue]?,<ios><xcode><swift>,1,...,NaN,NaN,34552617.0,2.0,2.0,80140.0,5337.0,2008-09-30 02:31:01,2017-11-12 15:58:51,"[make, app, tell, much, medicin, anim, need, b..."
22,34552614,1,2016-01-01 00:13:26,NaN,-1,123,<p>Once a Project is uploaded/Created in Proje...,How to Copy Projects in Project Web App for Of...,<project><office365><ms-project>,1,...,NaN,NaN,34667444.0,0.0,0.0,533.0,50.0,2012-11-21 19:26:05,2017-11-12 15:58:51,"[project, upload, creat, project, web, app, of..."
23,34552623,1,2016-01-01 00:15:55,NaN,4,673,"<p>So I'm watching tutorials on Code School, a...",HTML/CSS - How to get label inside form to ani...,<html><css>,1,...,1.0,NaN,34552657.0,8.0,8.0,127676.0,14559.0,2013-08-13 21:08:35,2017-11-12 15:58:51,"[i'm, watch, tutori, code, school, tutori, ani..."
24,34552550,1,2016-01-01 00:00:03,NaN,0,131,<p>Another newbie question. I am trying to und...,Scope between methods,<objective-c><scope>,1,...,NaN,NaN,34552570.0,1.0,1.0,80140.0,5337.0,2008-09-30 02:31:01,2017-11-12 15:58:51,"[anoth, newbi, question, tri, understand, use,..."
25,34552567,1,2016-01-01 00:03:46,NaN,3,1373,<p>When the timepicker control is inside a for...,How to get ui.bootstrap timepicker control to ...,<angularjs><twitter-bootstrap><angular-ui-boot...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[timepick, control, insid, form, initi, 'valid..."
26,34552593,1,2016-01-01 00:10:06,NaN,0,78,<p>I have embedded a youtube video as shown <a...,Java Swing: focus JWebBrowser and press space ...,<java><swing><youtube><djnativeswing><jwebbrow...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[embed, youtub, video, shown, sever, video, on..."
27,34552600,1,2016-01-01 00:11:01,NaN,1,44,<p>I just got a basic Node.js site up and runn...,Can't style body in style.css (Node.js),<html><css><node.js><express><mean-stack>,1,...,NaN,NaN,34552721.0,1.0,1.0,477.0,63.0,2014-09-24 02:58:32,2017-11-12 15:58:51,"[got, basic, node, js, site, run, run, strang,..."
28,34552642,1,2016-01-01 00:19:19,NaN,1,151,<p><code>Orders</code> is 350k rows. <code>Use...,Joining on table-valued function slows down query,<sql-server-2008><sql-execution-plan>,1,...,NaN,NaN,34552674.0,1.0,1.0,8202.0,1114.0,2011-06-20 16:01:47,2017-11-12 15:58:51,"[order, 350k, row, user, 20k, row, reflink, 2k..."
29,34552629,1,2016-01-01 00:17:17,NaN,1,715,<p>I currently have a test suite using Nunit a...,Run adiitional cleanup function on test failur...,<c#><unit-testing><selenium><nunit><assert>,1,...,NaN,NaN,34552728.0,1.0,1.0,339.0,7.0,2012-08-21 15:39:53,2017-11-12 15:58:51,"[current, test, suit, use, nunit, c, selenium,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,34706961,1,2016-01-10 15:08:07,NaN,1,542,"<p>CodePen link: <a href=""http://codepen.io/mr...",The collapsed navigation bar button is not exp...,<twitter-bootstrap>,1,...,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,2017-11-12 15:58:51,"[codepen, link, http, codepen, io, mraduldubey..."
49971,34706972,1,2016-01-10 15:08:49,NaN,2,245,<p>How can I just simple install apache2 packa...,simple shell inline provisionning,<ubuntu><vagrant><packer>,1,...,NaN,NaN,34711729.0,1.0,1.0,1486.0,137.0,2015-12-27 21:21:41,2017-11-12 15:58:51,"[simpl, instal, apache2, packag, packer, templ..."
49972,34707012,1,2016-01-10 15:13:44,NaN,0,32,<p>We are currently in process of development ...,Web server choice for SSJS,<javascript><node.js><web><ssjs>,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[current, process, develop, web, applic, ssj, ..."
49973,34707021,1,2016-01-10 15:14:26,NaN,2,385,<p>I am trying to compare a <code>combobox</co...,How to compare a combo box value with a table ...,<sql><sql-server><vb.net>,2,...,NaN,NaN,34707200.0,0.0,0.0,166234.0,11163.0,2016-04-06 07:18:54,2017-11-12 15:58:51,"[tri, compar, combobox, valu, data, store, alr..."
49974,34707035,1,2016-01-10 15:15:50,NaN,0,108,<p>I am trying to change the font in a WPF Ric...,How do I change the font in a WPF RichTextBox,<wpf><vb.net>,1,...,NaN,NaN,NaN,1.0,1.0,1324.0,43.0,2015-07-25 10:03:38,2017-11-12 15:58:51,"[tri, chang, font, wpf, richtextbox, use, net,..."
49975,34707037,1,2016-01-10 15:15:58,NaN,0,58,<p>There is certain part of the code in my pro...,Formatting in cpp,<c++><c++11><formatting>,1,...,NaN,NaN,34707130.0,1.0,1.0,251893.0,33860.0,2010-09-06 10:41:22,2017-11-12 15:58:51,"[certain, part, code, program, produc, result,..."
49976,34707060,1,2016-01-10 15:17:44,NaN,0,360,<p>Hi I'm using this following python parser t...,HTMLParser python turn data into string?,<python><html-parser>,2,...,NaN,NaN,NaN,0.0,0.0,513.0,58.0,2015-11-11 05:42:57,2017-11-12 15:58:51,"[hi, i'm, use, follow, python, parser, read, h..."
49977,34707070,1,2016-01-10 15:18:57,NaN,0,56,"<p>Been spending too much time on this..""f$%""\...",flat XML to nested using XSLT,<xml><xslt-2.0><xslt-grouping>,2,...,NaN,NaN,34710669.0,1.0,0.0,94519.0,3624.0,2010-04-15 00:08:03,2017-11-12 15:58:51,"[spend, much, time, f, hope, share, experi, so..."
49978,34707071,1,2016-01-10 15:19:02,NaN,-3,75,<p>I have the following piece of code as a pro...,List append comes out wrong,<python>,2,...,NaN,NaN,34707091.0,2.0,1.0,135488.0,9566.0,2014-11-12 16:31:01,2017-11-12 15:58:51,"[follow, piec, code, problem, list, 5, print, ..."
49979,34707079,1,2016-01-10 15:20:20,NaN,0,206,<p>I want to show website preview on a link si...,a website preview - loading a webpage using ja...,<javascript><c#><jquery><asp.net>,1,...,NaN,NaN,34711357.0,1.0,1.0,8051.0,606.0,2009-09-11 04:35:02,2017-11-12 15:58:51,"[want, show, websit, preview, link, similar, f..."
49980,34707139,1,2016-01-10 15:25:22,NaN,0,32,<p>I am working on a project in Java that invo...,javascript library in my Java project?,<javascript><java>,1,...,NaN,NaN,34707221.0,0.0,0.0,453.0,156.0,2012-05-25 17:49:20,2017-11-12 15:58:51,"[work, project, java, involv, design, speedome..."
49981,34707153,1,2016-01-10 15:26:17,NaN,0,483,"<p>I <a href=""https://stackoverflow.com/questi...",Don't reload the ngView template when I change...,<angularjs><ngroute>,1,...,NaN,NaN,34707213.0,1.0,1.0,755.0,46.0,2011-02-09 21:33:22,2017-11-12 15:58:51,"[post, question, recent, set, paramet, url, an..."
49982,34707164,1,2016-01-10 15:27:25,NaN,2,43,<p>I am a beginner in Angular and Rest and I h...,'Anonymous user' error after passing data with...,<angularjs><django><rest>,1,...,NaN,NaN,NaN,1.0,1.0,14840.0,2377.0,2011-08-20 14:17:50,2017-11-12 15:58:51,"[beginn, angular, rest, problem, form, django,..."
49983,34707178,1,2016-01-10 15:28:57,NaN,1,81,<p>Have a String given by:</p>\r\n\r\n<p>_xdyj...,Regular Expression Java,<java><regex>,2,...,NaN,NaN,34707633.0,0.0,0.0,1165.0,80.0,2016-01-09 21:50:50,2017-11-12 15:58:51,"[string, given, xdyjp, bn, qnp, 00, 00, 05, 94..."
49984,34707187,1,2016-01-10 15:29:51,NaN,2,38685,<p>I'm looking for simple bullet point answers...,What are some advantages and disadvantages for...,<javascript><html><html5><save><embedding>,2,...,1.0,NaN,34707580.0,3.0,2.0,1815.0,374.0,2015-04-10 11:55:42,2017-11-12 15:58:51,"[i'm, look, simpl, bullet, point, answer, plea..."
49985,34707194,1,2016-01-10 15:30:15,NaN,-2,61,<p>My table has 90 columns.</p>\r\n\r\n<p>How ...,How do I determine which column has been updated?,<sql-server>,2,...,NaN,NaN,NaN,0.0,0.0,11016.0,1356.0,2015-08-04 06:13:17,2017-11-12 15:58:51,"[tabl, 90, column, determin, column, updat, up..."
49986,34707197,1,2016-01-10 15:30:23,NaN,0,44,<p>using Python3.5\r\ni have two lists of stri...,"""multiplying"" two list of strings",<python><list><concatenation>,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[use, python3, 5, two, list, string, want, 'mu..."
49987,34707203,1,2016-01-10 15:30:53,NaN,1,1465,<p>I want to stringify a large object (to writ...,How to use JSONStream to stringify a large object,<json><node.js><stream>,1,...,NaN,NaN,34708135.0,2.0,2.0,5837.0,255.0,2015-09-29 11:48:35,2017-11-12 15:58:51,"[want, stringifi, larg, object, write, file, i..."
49988,34707219,1,2016-01-10 15:32:09,NaN,0,12,<p>I am concerned this may not be possible (at...,magento 1.4 - have different subdomain route t...,<php><apache><magento>,2,...,NaN,NaN,NaN,0.0,0.0,703.0,93.0,2012-11-04 19:52:57,2017-11-12 15:58:51,"[concern, may, possibl, least, easili, magento..."
49989,34707220,1,2016-01-10 15:32:23,NaN,-1,216,<p>I have started to use swashbuckle for my re...,Swashbuckle returns nullreferenceexception,<asp.net-web-api><swagger>,1,...,NaN,NaN,NaN,0.0,0.0,23.0,9.0,2015-09-30 17:35:00,2017-11-12 15:58:51,"[start, use, swashbuckl, rest, api, go, localh..."
49990,34707222,1,2016-01-10 15:32:25,NaN,0,70,<p>I have created such statement: </p>\r\n\r\n...,executeUpdate() does not add string variables,<java><database>,2,...,NaN,NaN,NaN,4.0,2.0,111824.0,13375.0,2015-11-03 10:06:59,2017-11-12 15:58:51,"[creat, statement, string, queri, insert, zmon..."
49991,34707236,1,2016-01-10 15:33:22,NaN,1,92,<p>I have to read a text file using this struc...,Structure as a parameter of extern function C,<c><function><structure><extern>,2,...,NaN,NaN,34707354.0,2.0,1.0,58955.0,1427.0,2014-07-18 12:16:05,2017-11-12 15:58:51,"[read, text, file, use, structur, also, use, e..."
49992,34707264,1,2016-01-10 15:35:28,NaN,1,885,<p>I'm trying to get ADC with DMA working on m...,STM32F4 ADC DMA config not working,<c><stm32><dma><adc>,1,...,NaN,NaN,NaN,2.0,2.0,46.0,10.0,2014-06-19 16:24:07,2017-11-12 15:58:51,"[i'm, tri, get, adc, dma, work, stm32f411re, n..."
49993,34707282,1,2016-01-10 15:37:29,NaN,0,28,<p>How can i calculate and print the result in...,Sum Multiple Text and Create New Column in R,<r>,1,...,NaN,NaN,34707292.0,0.0,0.0,302109.0,38967.0,2014-06-12 01:21:33,2017-11-12 15:58:51,"[calcul, print, result, new, column, case, hor..."
49994,34707342,1,2016-01-10 15:42:18,NaN,1,444,<p>I have a table with a column configured as ...,PLSQL - convert UTF-8 NVARCHAR2 to VARCHAR2,<utf-8><plsql>,1,...,0.0,NaN,34708855.0,1.0,1.0,812.0,37.0,2010-05-25 10:52:10,2017-11-12 15:58:51,"[tabl, column, configur, nvarchar2, i'm, abl, ..."
49995,34707383,1,2016-01-10 15:45:50,NaN,2,128,<p>I was trying to select a element using prot...,protractor Unexpected identifier for selector,<javascript><automated-tests><protractor>,1,...,1.0,NaN,34707396.0,1.0,1.0,273299.0,24409.0,2011-05-26 18:34:14,2017-11-12 15:58:51,"[tri, select, element, use, protractor, span, ..."
49996,34707385,1,2016-01-10 15:45:52,NaN,0,50,<p>i have this code:</p>\r\n\r\n<pre><code>pub...,LINQ Convert var collection to a specific coll...,<c#><linq><collections>,1,...,NaN,NaN,34707400.0,1.0,1.0,17756.0,1738.0,2012-07-16 17:48:52,2017-11-12 15:58:51,"[code, public, class, existedproduct, public, ..."
49997,34707280,1,2016-01-10 15:37:10,NaN,8,625,<p>Let's say I have this dictionary:</p>\r\n\r...,Selecting random values from dictionary,<python><dictionary><random>,3,...,1.0,NaN,34707337.0,13.0,8.0,139771.0,12359.0,2013-08-20 14:43:44,2017-11-12 15:58:51,"[let', say, dictionari, dict, 'a', 100, 'b', 5..."
49998,34707380,1,2016-01-10 15:45:41,NaN,0,376,<p>I'm writting an Android App and connect to ...,Connect Azure service bus on Android by Rest API,<java><android><azure>,1,...,NaN,NaN,NaN,0.0,0.0,9085.0,1140.0,2015-06-09 09:13:08,2017-11-12 15:58:51,"[i'm, writ, android, app, connect, azur, servi..."
49999,34707980,1,2016-01-10 12:50:01,NaN,1,145,<p>I have got a problem on my blog. I installe...,Recommended post slide out post widget not wor...,<javascript><blogger><blogspot>,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[got, problem, blog, instal, recommend, post, ..."

In [10]:
df = pd.DataFrame(data=data)

In [11]:
def calculate_positivity(text):
    num_tokens = len(text)
    num_positive_tokens = 0
    for t in text:
        if t in positive_terms:
            num_positive_tokens = num_positive_tokens + 1
    # The positivity score is the fraction of tokens that were found in the positive dictionary
    return float(num_positive_tokens) / float(num_tokens)

df["positivity_score"] = df["Body_text"].apply(calculate_positivity)

def calculate_negativity(text):
    num_tokens = len(text)
    num_negative_tokens = 0
    for t in text:
        if t in negative_terms:
            num_negative_tokens = num_negative_tokens + 1
    # The positivity score is the fraction of tokens that were found in the positive dictionary
    return float(num_negative_tokens) / float(num_tokens)

df["negativity_score"] = df["Body_text"].apply(calculate_negativity)
df

,PostId,X,PostCreation,PostDeletion,postScore,postViewcount,body,title,tags,numAnswer,...,AcceptedAnswerId,max_ans_score,avg_ans_score,AnswererReputation,answererProfileViews,answererRegistration,X.1,Body_text,positivity_score,negativity_score
0,34552551,1,2016-01-01 00:00:07,NaN,1,213,<p>Hello I am new to Rails.</p>\r\n\r\n<p>Here...,Rails - Unknown Attribute - Unable to add a ne...,<ruby><ruby-on-rails-4>,2,...,34554360.0,1.0,0.0,6791.0,682.0,2015-12-06 15:27:33,2017-11-12 15:58:51,"[hello, new, rail, control, project, control, ...",0.035971,0.014388
1,34552552,1,2016-01-01 00:00:39,NaN,2,2169,<p>everyone. </p>\r\n\r\n<p>Main question: I a...,Selenium Firefox webdriver won't load a blank ...,<python><firefox><selenium><selenium-webdriver>,1,...,34555040.0,2.0,2.0,106.0,3.0,2013-10-07 07:47:41,2017-11-12 15:58:51,"[everyon, main, question, use, python, api, se...",0.016000,0.008000
2,34552558,1,2016-01-01 00:01:27,NaN,1,237,<p><strong>What is it about ?</strong></p>\r\n...,Force delete Session records for the current l...,<laravel><laravel-5.1><laravel-5.2>,1,...,NaN,0.0,0.0,2060.0,2698.0,2010-02-15 13:10:04,2017-11-12 15:58:51,"[use, session, tabl, keep, accumul, current, u...",0.000000,0.000000
3,34552560,1,2016-01-01 00:01:50,NaN,0,39,<p>I just want to know which of this two struc...,Which data structure (full HABTM ?),<data-structures><has-and-belongs-to-many><has...,1,...,34552698.0,0.0,0.0,11.0,5.0,2014-04-16 09:02:57,2017-11-12 15:58:51,"[want, know, two, structur, best, better, perf...",0.037037,0.000000
4,34552610,1,2016-01-01 00:12:53,NaN,-1,311,<p>I'm using this echo statement in a php scri...,Adding ternary operator in echo statement,<php>,3,...,34552768.0,1.0,1.0,133096.0,14559.0,2015-12-27 21:21:41,2017-11-12 15:58:51,"[i'm, use, echo, statement, php, script, work,...",0.049180,0.000000
5,34552625,1,2016-01-01 00:16:26,NaN,1,3246,<p>In the DynamoDB documentation and in many p...,How to get sub 10ms response times from AWS Dy...,<amazon-web-services><amazon-dynamodb>,3,...,34557194.0,8.0,4.0,2750.0,105.0,2017-01-27 19:38:43,2017-11-12 15:58:51,"[dynamodb, document, mani, place, around, inte...",0.011628,0.011628
6,34552653,1,2016-01-01 00:21:42,NaN,0,2273,"<p>I am on a Raspberry Pi, and I am using a pr...",Execute terminal commands in python3,<python><python-3.x><raspberry-pi><subprocess>...,1,...,34552734.0,5.0,5.0,1042.0,194.0,2014-12-26 23:50:53,2017-11-12 15:58:51,"[raspberri, pi, use, program, call, fswebcam, ...",0.021739,0.000000
7,34552554,1,2016-01-01 00:00:50,NaN,0,237,<p>Ever since I updated android studio to the ...,Android Studio styles.xml Error,<android><android-studio>,2,...,NaN,0.0,0.0,1287.0,204.0,2015-12-16 21:48:30,2017-11-12 15:58:51,"[ever, sinc, updat, android, studio, newest, v...",0.014493,0.043478
8,34552557,1,2016-01-01 00:01:12,NaN,1,28,<p>I've been trying to set up Forem (a Rails 4...,How to namespace routes in Rails 4 to set up F...,<ruby-on-rails><ruby-on-rails-4><routes><forem>,1,...,NaN,1.0,1.0,117.0,20.0,2010-11-13 21:10:13,2017-11-12 15:58:51,"[i'v, tri, set, forem, rail, 4, forum, engin, ...",0.000000,0.000000
9,34552565,1,2016-01-01 00:02:53,NaN,2,592,<p>Please read the question before marking thi...,Is there a way to use flashlight on in Android...,<java><android><android-camera><flashlight><im...,2,...,NaN,1.0,0.0,31360.0,4723.0,2011-10-06 12:34:46,2017-11-12 15:58:51,"[pleas, read, question, mark, duplic, i'm, tri...",0.027027,0.004505
10,34552587,1,2016-01-01 00:08:12,NaN,0,139,"<p>I have a Mac with OS 10.11.1, from which I ...",Using gnuplot remotely from Mac,<osx><gnuplot>,0,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[mac, os, 10, 11, 1, ssh, use, termin, option,...",0.000000,0.028571
11,34552615,1,2016-01-01 00:13:52,NaN,0,163,<p>I'm creating custom functions for sign up a...,Programatically adding product to magento cart...,<magento>,1,...,34562412.0,0.0,0.0,351.0,38.0,2012-01-30 13:05:18,2017-11-12 15:58:51,"[i'm, creat, custom, function, sign, ad, produ...",0.026923,0.000000
12,34552555,1,2016-01-01 00:00:51,NaN,-1,61,<p>I am creating some Java codes like the foll...,Java: reference to non-finial local variables ...,<java><multithreading><local-variables>,2,...,NaN,1.0,0.0,64835.0,10832.0,2011-11-04 14:46:54,2017-11-12 15:58:51,"[creat, java, code, like, follow, new, thread,...",0.039062,0.007812
13,34552563,1,2016-01-01 00:02:22,NaN,2,942,<p>I'm using the PHP build system <code>phing<...,"PHP: Phing, Phar, and phar.readonly",<php><phing><phar>,1,...,NaN,5.0,5.0,51.0,2.0,2016-01-31 23:11:43,2017-11-12 15:58:51,"[i'm, use, php, build, system, phing, creat, p...",0.000000,0.000000
14,34552589,1,2016-01-01 00:08:22,NaN,0,575,<p>I have review many examples but have not be...,mvc partial view autocomplete using modal jque...,<c#><jquery><asp.net-mvc>,1,...,NaN,0.0,0.0,120911.0,6341.0,2008-11-25 05:29:48,2017-11-12 15:58:51,"[review, mani, exampl, abl, find, exampl, help...",0.008439,0.004219
15,34552661,1,2016-01-01 00:23:40,NaN,0,25,<p>I have a table that shows a list of prescri...,Rails - Trying to check if a column is empty b...,<ruby-on-rails-4><ruby-on-rails-3.2>,1,...,34552771.0,0.0,0.0,2449.0,135.0,2014-06-24 22:07:53,2017-11-12 15:58:51,"[tabl, show, list, prescript, want, filter, pr...",0.018868,0.000000
16,34552711,1,2016-01-01 00:36:29,NaN,0,49,<p>In my model I'm receiving a property that's...,Converting an int into a set of columns with R...,<c#><razor><flags>,1,...,34553592.0,1.0,1.0,2149.0,144.0,2012-10-27 01:27:34,2017-11-12 15:58:51,"[model, i'm, receiv, properti, that', integ, c...",0.006803,0.000000
17,34552719,1,2016-01-01 00:39:36,NaN,0,171,<p>I'm writing an iOS app that has two views. ...,Two RCTRootView instances in one app,<ios><react-native>,1,...,34559063.0,0.0,0.0,743.0,76.0,2012-09-27 00:17:03,2017-11-12 15:58:51,"[i'm, write, io, app, two, view, view, rctroot...",0.041667,0.027778
18,34552733,1,2016-01-01 00:42:07,NaN,1,779,<p>I loaded content with divs dynamically via ...,addEventListener not working for ajax generate...,<javascript><ajax>,1,...,NaN,0.0,0.0,781.0,475.0,2015-08-09 14:41:32,2017-11-12 15:58:51,"[load, content, div, dynam, via, ajax, pure, j...",0.032787,0.016393
19,34552584,1,2016-01-01 00:07:19,NaN,1,339,<p>Happy new year to all of you!\r\nI trained ...,Is there any chance I got memory leak with pyt...,<python><memory-management><memory-leaks><theano>,0,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[happi, new, year, train, deep, learn, model, ...",0.044715,0.004065
20,34552603,1,2016-01-01 00:11:37,NaN,0,61,<p>I have a imageview that randomly generate 1...,If statement depending on the random image shown,<android><random>,1,...,34553435.0,0.0,0.0,1794.0,117.0,2013-09-21 02:51:49,2017-11-12 15:58:51,"[imageview, randomli, gener, 1, 2, possibl, im...",0.004695,0.004695
21,34552612,1,2016-01-01 00:13:10,NaN,0,42,<p>I am making an app that tells you how much ...,How do I impliment [example.text intValue]?,<ios><xcode><swift>,1,...,34552617.0,2.0,2.0,80140.0,5337.0,2008-09-30 02:31:01,2017-11-12 15:58:51,"[make, app, tell, much, medicin, anim, need, b...",0.014563,0.063107
22,34552614,1,2016-01-01 00:13:26,NaN,-1,123,<p>Once a Project is uploaded/Created in Proje...,How to Copy Projects in Project Web App for Of...,<project><office365><ms-project>,1,...,34667444.0,0.0,0.0,533.0,50.0,2012-11-21 19:26:05,2017-11-12 15:58:51,"[project, upload, creat, project, web, app, of...",0.035714,0.000000
23,34552623,1,2016-01-01 00:15:55,NaN,4,673,"<p>So I'm watching tutorials on Code School, a...",HTML/CSS - How to get label inside form to ani...,<html><css>,1,...,34552657.0,8.0,8.0,127676.0,14559.0,2013-08-13 21:08:35,2017-11-12 15:58:51,"[i'm, watch, tutori, code, school, tutori, ani...",0.027273,0.009091
24,34552550,1,2016-01-01 00:00:03,NaN,0,131,<p>Another newbie question. I am trying to und...,Scope between methods,<objective-c><scope>,1,...,34552570.0,1.0,1.0,80140.0,5337.0,2008-09-30 02:31:01,2017-11-12 15:58:51,"[anoth, newbi, question, tri, understand, use,...",0.014742,0.000000
25,34552567,1,2016-01-01 00:03:46,NaN,3,1373,<p>When the timepicker control is inside a for...,How to get ui.bootstrap timepicker control to ...,<angularjs><twitter-bootstrap><angular-ui-boot...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[timepick, control, insid, form, initi, 'valid...",0.036697,0.000000
26,34552593,1,2016-01-01 00:10:06,NaN,0,78,<p>I have embedded a youtube video as shown <a...,Java Swing: focus JWebBrowser and press space ...,<java><swing><youtube><djnativeswing><jwebbrow...,0,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[embed, youtub, video, shown, sever, video, on...",0.017544,0.017544
27,34552600,1,2016-01-01 00:11:01,NaN,1,44,<p>I just got a basic Node.js site up and runn...,Can't style body in style.css (Node.js),<html><css><node.js><express><mean-stack>,1,...,34552721.0,1.0,1.0,477.0,63.0,2014-09-24 02:58:32,2017-11-12 15:58:51,"[got, basic, node, js, site, run, run, strang,...",0.000000,0.010989
28,34552642,1,2016-01-01 00:19:19,NaN,1,151,<p><code>Orders</code> is 350k rows. <code>Use...,Joining on table-valued function slows down query,<sql-server-2008><sql-execution-plan>,1,...,34552674.0,1.0,1.0,8202.0,1114.0,2011-06-20 16:01:47,2017-11-12 15:58:51,"[order, 350k, row, user, 20k, row, reflink, 2k...",0.007519,0.000000
29,34552629,1,2016-01-01 00:17:17,NaN,1,715,<p>I currently have a test suite using Nunit a...,Run adiitional cleanup function on test failur...,<c#><unit-testing><selenium><nunit><assert>,1,...,34552728.0,1.0,1.0,339.0,7.0,2012-08-21 15:39:53,2017-11-12 15:58:51,"[current, test, suit, use, nunit, c, selenium,...",0.062500,0.062500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49970,34706961,1,2016-01-10 15:08:07,NaN,1,542,"<p>CodePen link: <a href=""http://codepen.io/mr...",The collapsed navigation bar button is not exp...,<twitter-bootstrap>,1,...,NaN,0.0,0.0,NaN,NaN,NaN,2017-11-12 15:58:51,"[codepen, link, http, codepen, io, mraduldubey...",0.000000,0.000000
49971,34706972,1,2016-01-10 15:08:49,NaN,2,245,<p>How can I just simple install apache2 packa...,simple shell inline provisionning,<ubuntu><vagrant><packer>,1,...,34711729.0,1.0,1.0,1486.0,137.0,2015-12-27 21:21:41,2017-11-12 15:58:51,"[simpl, instal, apache2, packag, packer, templ...",0.005935,0.002967
49972,34707012,1,2016-01-10 15:13:44,NaN,0,32,<p>We are currently in process of development ...,Web server choice for SSJS,<javascript><node.js><web><ssjs>,0,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[current, process, develop, web, applic, ssj, ...",0.000000,0.000000
49973,34707021,1,2016-01-10 15:14:26,NaN,2,385,<p>I am trying to compare a <code>combobox</co...,How to compare a combo box value with a table ...,<sql><sql-server><vb.net>,2,...,34707200.0,0.0,0.0,166234.0,11163.0,2016-04-06 07:18:54,2017-11-12 15:58:51,"[tri, compar, combobox, valu, data, store, alr...",0.019108,0.000000
49974,34707035,1,2016-01-10 15:15:50,NaN,0,108,<p>I am trying to change the font in a WPF Ric...,How do I change the font in a WPF RichTextBox,<wpf><vb.net>,1,...,NaN,1.0,1.0,1324.0,43.0,2015-07-25 10:03:38,2017-11-12 15:58:51,"[tri, chang, font, wpf, richtextbox, use, net,...",0.000000,0.000000
49975,34707037,1,2016-01-10 15:15:58,NaN,0,58,<p>There is certain part of the code in my pro...,Formatting in cpp,<c++><c++11><formatting>,1,...,34707130.0,1.0,1.0,251893.0,33860.0,2010-09-06 10:41:22,2017-11-12 15:58:51,"[certain, part, code, program, produc, result,...",0.018634,0.000000
49976,34707060,1,2016-01-10 15:17:44,NaN,0,360,<p>Hi I'm using this following python parser t...,HTMLParser python turn data into string?,<python><html-parser>,2,...,NaN,0.0,0.0,513.0,58.0,2015-11-11 05:42:57,2017-11-12 15:58:51,"[hi, i'm, use, follow, python, parser, read, h...",0.005882,0.000000
49977,34707070,1,2016-01-10 15:18:57,NaN,0,56,"<p>Been spending too much time on this..""f$%""\...",flat XML to nested using XSLT,<xml><xslt-2.0><xslt-grouping>,2,...,34710669.0,1.0,0.0,94519.0,3624.0,2010-04-15 00:08:03,2017-11-12 15:58:51,"[spend, much, time, f, hope, share, experi, so...",0.006711,0.005369
49978,34707071,1,2016-01-10 15:19:02,NaN,-3,75,<p>I have the following piece of code as a pro...,List append comes out wrong,<python>,2,...,34707091.0,2.0,1.0,135488.0,9566.0,2014-11-12 16:31:01,2017-11-12 15:58:51,"[follow, piec, code, problem, list, 5, print, ...",0.000000,0.032258
49979,34707079,1,2016-01-10 15:20:20,NaN,0,206,<p>I want to show website preview on a link si...,a website preview - loading a webpage using ja...,<javascript><c#><jquery><asp.net>,1,...,34711357.0,1.0,1.0,8051.0,606.0,2009-09-11 04:35:02,2017-11-12 15:58:51,"[want, show, websit, preview, link, similar, f...",0.006410,0.019231
49980,34707139,1,2016-01-10 15:25:22,NaN,0,32,<p>I am working on a project in Java that invo...,javascript library in my Java project?,<javascript><java>,1,...,34707221.0,0.0,0.0,453.0,156.0,2012-05-25 17:49:20,2017-11-12 15:58:51,"[work, project, java, involv, design, speedome...",0.000000,0.000000
49981,34707153,1,2016-01-10 15:26:17,NaN,0,483,"<p>I <a href=""https://stackoverflow.com/questi...",Don't reload the ngView template when I change...,<angularjs><ngroute>,1,...,34707213.0,1.0,1.0,755.0,46.0,2011-02-09 21:33:22,2017-11-12 15:58:51,"[post, question, recent, set, paramet, url, an...",0.021390,0.016043
49982,34707164,1,2016-01-10 15:27:25,NaN,2,43,<p>I am a beginner in Angular and Rest and I h...,'Anonymous user' error after passing data with...,<angularjs><django><rest>,1,...,NaN,1.0,1.0,14840.0,2377.0,2011-08-20 14:17:50,2017-11-12 15:58:51,"[beginn, angular, rest, problem, form, django,...",0.026961,0.004902
49983,34707178,1,2016-01-10 15:28:57,NaN,1,81,<p>Have a String given by:</p>\r\n\r\n<p>_xdyj...,Regular Expression Java,<java><regex>,2,...,34707633.0,0.0,0.0,1165.0,80.0,2016-01-09 21:50:50,2017-11-12 15:58:51,"[string, given, xdyjp, bn, qnp, 00, 00, 05, 94...",0.010101,0.010101
49984,34707187,1,2016-01-10 15:29:51,NaN,2,38685,<p>I'm looking for simple bullet point answers...,What are some advantages and disadvantages for...,<javascript><html><html5><save><embedding>,2,...,34707580.0,3.0,2.0,1815.0,374.0,2015-04-10 11:55:42,2017-11-12 15:58:51,"[i'm, look, simpl, bullet, point, answer, plea...",0.058824,0.000000
49985,34707194,1,2016-01-10 15:30:15,NaN,-2,61,<p>My table has 90 columns.</p>\r\n\r\n<p>How ...,How do I determine which column has been updated?,<sql-server>,2,...,NaN,0.0,0.0,11016.0,1356.0,2015-08-04 06:13:17,2017-11-12 15:58:51,"[tabl, 90, column, determin, column, updat, up...",0.000000,0.000000
49986,34707197,1,2016-01-10 15:30:23,NaN,0,44,<p>using Python3.5\r\ni have two lists of stri...,"""multiplying"" two list of strings",<python><list><concatenation>,0,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[use, python3, 5, two, list, string, want, 'mu...",0.000000,0.000000
49987,34707203,1,2016-01-10 15:30:53,NaN,1,1465,<p>I want to stringify a large object (to writ...,How to use JSONStream to stringify a large object,<json><node.js><stream>,1,...,34708135.0,2.0,2.0,5837.0,255.0,2015-09-29 11:48:35,2017-11-12 15:58:51,"[want, stringifi, larg, object, write, file, i...",0.000000,0.000000
49988,34707219,1,2016-01-10 15:32:09,NaN,0,12,<p>I am concerned this may not be possible (at...,magento 1.4 - have different subdomain route t...,<php><apache><magento>,2,...,NaN,0.0,0.0,703.0,93.0,2012-11-04 19:52:57,2017-11-12 15:58:51,"[concern, may, possibl, least, easili, magento...",0.000000,0.000000
49989,34707220,1,2016-01-10 15:32:23,NaN,-1,216,<p>I have started to use swashbuckle for my re...,Swashbuckle returns nullreferenceexception,<asp.net-web-api><swagger>,1,...,NaN,0.0,0.0,23.0,9.0,2015-09-30 17:35:00,2017-11-12 15:58:51,"[start, use, swashbuckl, rest, api, go, localh...",0.031250,0.000000
49990,34707222,1,2016-01-10 15:32:25,NaN,0,70,<p>I have created such statement: </p>\r\n\r\n...,executeUpdate() does not add string variables,<java><database>,2,...,NaN,4.0,2.0,111824.0,13375.0,2015-11-03 10:06:59,2017-11-12 15:58:51,"[creat, statement, string, queri, insert, zmon...",0.000000,0.000000
49991,34707236,1,2016-01-10 15:33:22,NaN,1,92,<p>I have to read a text file using this struc...,Structure as a parameter of extern function C,<c><function><structure><extern>,2,...,34707354.0,2.0,1.0,58955.0,1427.0,2014-07-18 12:16:05,2017-11-12 15:58:51,"[read, text, file, use, structur, also, use, e...",0.005376,0.000000
49992,34707264,1,2016-01-10 15:35:28,NaN,1,885,<p>I'm trying to get ADC with DMA working on m...,STM32F4 ADC DMA config not working,<c><stm32><dma><adc>,1,...,NaN,2.0,2.0,46.0,10.0,2014-06-19 16:24:07,2017-11-12 15:58:51,"[i'm, tri, get, adc, dma, work, stm32f411re, n...",0.000000,0.006024
49993,34707282,1,2016-01-10 15:37:29,NaN,0,28,<p>How can i calculate and print the result in...,Sum Multiple Text and Create New Column in R,<r>,1,...,34707292.0,0.0,0.0,302109.0,38967.0,2014-06-12 01:21:33,2017-11-12 15:58:51,"[calcul, print, result, new, column, case, hor...",0.086957,0.000000
49994,34707342,1,2016-01-10 15:42:18,NaN,1,444,<p>I have a table with a column configured as ...,PLSQL - convert UTF-8 NVARCHAR2 to VARCHAR2,<utf-8><plsql>,1,...,34708855.0,1.0,1.0,812.0,37.0,2010-05-25 10:52:10,2017-11-12 15:58:51,"[tabl, column, configur, nvarchar2, i'm, abl, ...",0.028571,0.000000
49995,34707383,1,2016-01-10 15:45:50,NaN,2,128,<p>I was trying to select a element using prot...,protractor Unexpected identifier for selector,<javascript><automated-tests><protractor>,1,...,34707396.0,1.0,1.0,273299.0,24409.0,2011-05-26 18:34:14,2017-11-12 15:58:51,"[tri, select, element, use, protractor, span, ...",0.066667,0.044444
49996,34707385,1,2016-01-10 15:45:52,NaN,0,50,<p>i have this code:</p>\r\n\r\n<pre><code>pub...,LINQ Convert var collection to a specific coll...,<c#><linq><collections>,1,...,34707400.0,1.0,1.0,17756.0,1738.0,2012-07-16 17:48:52,2017-11-12 15:58:51,"[code, public, class, existedproduct, public, ...",0.000000,0.013889
49997,34707280,1,2016-01-10 15:37:10,NaN,8,625,<p>Let's say I have this dictionary:</p>\r\n\r...,Selecting random values from dictionary,<python><dictionary><random>,3,...,34707337.0,13.0,8.0,139771.0,12359.0,2013-08-20 14:43:44,2017-11-12 15:58:51,"[let', say, dictionari, dict, 'a', 100, 'b', 5...",0.000000,0.000000
49998,34707380,1,2016-01-10 15:45:41,NaN,0,376,<p>I'm writting an Android App and connect to ...,Connect Azure service bus on Android by Rest API,<java><android><azure>,1,...,NaN,0.0,0.0,9085.0,1140.0,2015-06-09 09:13:08,2017-11-12 15:58:51,"[i'm, writ, android, app, connect, azur, servi...",0.030928,0.000000
49999,34707980,1,2016-01-10 12:50:01,NaN,1,145,<p>I have got a problem on my blog. I installe...,Recommended post slide out post widget not wor...,<javascript><blogger><blogspot>,0,...,NaN,NaN,NaN,NaN,NaN,NaN,2017-11-12 15:58:51,"[got, problem, blog, instal, recommend, post, ...",0.005722,0.001431

In [12]:
df.to_csv('df_data1112_no_html.csv')